version: "3.7"

services:
  traefik:
    container_name: traefik-home
    image: "traefik:latest"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "8080:8080/tcp"
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "9091:9091/tcp"
      - "51413:51413/tcp"
      - "51413:51413/udp"

    restart: "${RESTART}"  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./ssl:/certs
      - ./traefik/ssl.yml:/etc/ssl.yml
    environment:
      - TZ=${TZ}
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIKURL}`)"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`${TRAEFIKURL}`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    expose:
      - "443"
      - "80"
      # - "53/tcp"
      # - "53/udp"
      # - "67/udp"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      #Set UID and GID has not been implemeted. Issue #328 on github
      - TZ=${TZ}
    volumes:
       - './pihole/etc-pihole/:/etc/pihole/'
       - './pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # run `touch ./var-log/pihole.log` first unless you like errors
    # - './var-log/pihole.log:/var/log/pihole.log'
    dns:
      - 1.1.1.1
      - 8.8.8.8
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: ${RESTART}
    labels: 
      - "traefik.enable=true"

      - "traefik.http.routers.pihole.entrypoints=web"
      - "traefik.http.routers.pihole.rule=Host(`${PIHOLEURL}`)"
      - "traefik.http.routers.pihole.service=pihole"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"

      - "traefik.http.routers.pihole.middlewares=traefik-https-redirect"
      - "traefik.http.middlewares.pihole-https-redirect.redirectscheme.scheme=https"

      - "traefik.http.routers.pihole-secure.entrypoints=websecure"
      - "traefik.http.routers.pihole-secure.rule=Host(`${PIHOLEURL}`)"
      - "traefik.http.routers.pihole-secure.tls=true"
      - "traefik.http.routers.pihole-secure.service=pihole"
  transmission:
      image: lscr.io/linuxserver/transmission:latest
      container_name: transmission
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        - UMASK_SET=022 #optional
        - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
        - USER=admin #optional
        - PASS=torrent #optional
        - WHITELIST=iplist #optional
        - PEERPORT=peerport #optional
        - HOST_WHITELIST=dnsname list #optional
      volumes:
        - ./transmission/data:/config
        - /home/docker/nas-share/TDDOWNLOAD/transmission/transmission:/downloads
        - /home/docker/nas-share/TDDOWNLOAD/transmission/watch:/watch
      #ports:
      #  - 9091:9091
      #  - 51413:51413
      #  - 51413:51413/udp
      restart: unless-stopped
      labels: 
      - "traefik.enable=true"

      - "traefik.http.routers.transmission.entrypoints=web"
      - "traefik.http.routers.transmission.rule=Host(`${TRANSURL}`)"


      - "traefik.http.routers.transmission.middlewares=traefik-https-redirect"
      - "traefik.http.middlewares.transmission-https-redirect.redirectscheme.scheme=https"

      - "traefik.http.services.transmission.loadbalancer.server.port=9091"

      - "traefik.http.routers.transmission-secure.entrypoints=websecure"
      - "traefik.http.routers.transmission-secure.rule=Host(`${TRANSURL}`)"
      - "traefik.http.routers.transmission-secure.tls=true"
      - "traefik.http.routers.transmission-secure.service=transmission"

      - "traefik.tcp.routers.transmission1.entrypoints=transmission1"
      - "traefik.tcp.routers.transmission1.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.transmission1.service=transmission1"
      - "traefik.tcp.services.transmission1.loadbalancer.server.port=51413"

      - "traefik.udp.routers.transmission2.entrypoints=transmission2"
      - "traefik.udp.routers.transmission2.service=transmission2"
      - "traefik.udp.services.transmission2.loadbalancer.server.port=51413"

  nzbget:
    container_name: nzbget_new
    image: linuxserver/nzbget:latest
    expose:
      - "6789"
    dns: "${DNS}"
    volumes:
      - ./nzbget/config:/config
      - ${NZBDOWNLOADS}:/downloads
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: ${RESTART}
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.nzbget.entrypoints=web"
      - "traefik.http.routers.nzbget.rule=Host(`${NZBGETURL}`)"

      - "traefik.http.routers.nzbget.middlewares=nzbget-https-redirect"
      - "traefik.http.middlewares.nzbget-https-redirect.redirectscheme.scheme=https"

      - "traefik.http.services.nzbget.loadbalancer.server.port=6789"

      - "traefik.http.routers.nzbget-secure.entrypoints=websecure"
      - "traefik.http.routers.nzbget-secure.rule=Host(`${NZBGETURL}`)"
      - "traefik.http.routers.nzbget-secure.tls=true"
      - "traefik.http.routers.nzbget-secure.service=nzbget"
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
    volumes:
      - ./radarr:/config
      - ${MOVIES}:/movies
      - ${NZBDOWNLOADS}:/downloads
    ports:
      - 7878:7878
    dns: "${DNS}"
    restart: "${RESTART}"
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entrypoints=web"
      - "traefik.http.routers.radarr.rule=Host(`${RADARRURL}`)"

      - "traefik.http.routers.radarr.middlewares=radarr-https-redirect"
      - "traefik.http.middlewares.radarr-https-redirect.redirectscheme.scheme=https"

      - "traefik.http.services.radarr.loadbalancer.server.port=7878"

      - "traefik.http.routers.radarr-secure.entrypoints=websecure"
      - "traefik.http.routers.radarr-secure.rule=Host(`${RADARRURL}`)"
      - "traefik.http.routers.radarr-secure.tls=true"
      - "traefik.http.routers.radarr-secure.service=radarr"
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
    volumes:
      - ./sonarr:/config
      - ${TV}:/tv
      - ${NZBDOWNLOADS}:/downloads
    ports:
      - 8989:8989
    dns: "${DNS}"
    restart: "${RESTART}"
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.entrypoints=web"
      - "traefik.http.routers.sonarr.rule=Host(`${SONARRURL}`)"

      - "traefik.http.routers.sonarr.middlewares=sonarr-https-redirect"
      - "traefik.http.middlewares.sonarr-https-redirect.redirectscheme.scheme=https"

      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"

      - "traefik.http.routers.sonarr-secure.entrypoints=websecure"
      - "traefik.http.routers.sonarr-secure.rule=Host(`${SONARRURL}`)"
      - "traefik.http.routers.sonarr-secure.tls=true"
      - "traefik.http.routers.sonarr-secure.service=sonarr"
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
    volumes:
      - ./bazarr:/config
      - ${MOVIES}:/movies
      - ${TV}:/tv
      - ${NZBDOWNLOADS}:/downloads
    dns: "${DNS}"
    ports:
      - 6767:6767
    restart: unless-stopped
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.entrypoints=web"
      - "traefik.http.routers.bazarr.rule=Host(`${BAZARRURL}`)"

      - "traefik.http.routers.bazarr.middlewares=bazarr-https-redirect"
      - "traefik.http.middlewares.bazarr-https-redirect.redirectscheme.scheme=https"

      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"

      - "traefik.http.routers.bazarr-secure.entrypoints=websecure"
      - "traefik.http.routers.bazarr-secure.rule=Host(`${BAZARRURL}`)"
      - "traefik.http.routers.bazarr-secure.tls=true"
      - "traefik.http.routers.bazarr-secure.service=bazarr"
  nzbhydra2:
    image: linuxserver/nzbhydra2
    container_name: nzbhydra2
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ./nzbhydra2:/config
      - ${NZBDOWNLOADS}:/downloads
    dns: "${DNS}"
    ports:
      - 5076:5076
    restart: unless-stopped
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.hydra.entrypoints=web"
      - "traefik.http.routers.hydra.rule=Host(`${HYDRAURL}`)"

      - "traefik.http.routers.hydra.middlewares=hydra-https-redirect"
      - "traefik.http.middlewares.hydra-https-redirect.redirectscheme.scheme=https"

      - "traefik.http.services.hydra.loadbalancer.server.port=5076"

      - "traefik.http.routers.hydra-secure.entrypoints=websecure"
      - "traefik.http.routers.hydra-secure.rule=Host(`${HYDRAURL}`)"
      - "traefik.http.routers.hydra-secure.tls=true"
      - "traefik.http.routers.hydra-secure.service=hydra"
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    dns: ${DNS}
    environment:
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - VERSION=docker
      - UMASK_SET=022
      - ADVERTISE_IP=https://${ADVERTISE_IP}:32400/
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
    #network_mode: host
    volumes:
      - ./plex/config:/config
      - ./plex/transcode:/transcode
      - ${MOVIES}:/data
      - ${MOVIES}:/movies
      - ${TV}:/tv
      - ${XXX}:/xxx
    restart: "${RESTART}"
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.plex.entrypoints=web"
      - "traefik.http.routers.plex.rule=Host(`${PLEXURL}`)"

      - "traefik.http.routers.plex.middlewares=plex-https-redirect"
      - "traefik.http.middlewares.plex-https-redirect.redirectscheme.scheme=https"

      - "traefik.http.services.plex.loadbalancer.server.port=32400"

      - "traefik.http.routers.plex-secure.entrypoints=websecure"
      - "traefik.http.routers.plex-secure.rule=Host(`${PLEXURL}`)"
      - "traefik.http.routers.plex-secure.tls=true"
      - "traefik.http.routers.plex-secure.service=plex"

      - "traefik.tcp.routers.plexweb.entrypoints=plexweb"
      - "traefik.tcp.routers.plexweb.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.plexweb.service=plexweb"
      - "traefik.tcp.services.plexweb.loadbalancer.server.port=32400"

      - "traefik.tcp.routers.plex1.entrypoints=plex1"
      - "traefik.tcp.routers.plex1.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.plex1.service=plex1"
      - "traefik.tcp.services.plex1.loadbalancer.server.port=3005"

      - "traefik.tcp.routers.plex2.entrypoints=plex2"
      - "traefik.tcp.routers.plex2.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.plex2.service=plex2"
      - "traefik.tcp.services.plex2.loadbalancer.server.port=8324"

      - "traefik.tcp.routers.plex3.entrypoints=plex3"
      - "traefik.tcp.routers.plex3.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.plex3.service=plex3"
      - "traefik.tcp.services.plex3.loadbalancer.server.port=32469"

      - "traefik.udp.routers.plex4.entrypoints=plex4"
      - "traefik.udp.routers.plex4.service=plex4"
      - "traefik.udp.services.plex4.loadbalancer.server.port=1900"

      - "traefik.udp.routers.plex5.entrypoints=plex5"
      - "traefik.udp.routers.plex5.service=plex5"
      - "traefik.udp.services.plex5.loadbalancer.server.port=32410"
      
      - "traefik.udp.routers.plex6.entrypoints=plex6"
      - "traefik.udp.routers.plex6.service=plex6"
      - "traefik.udp.services.plex6.loadbalancer.server.port=32412"

      - "traefik.udp.routers.plex7.entrypoints=plex7"
      - "traefik.udp.routers.plex7.service=plex7"
      - "traefik.udp.services.plex7.loadbalancer.server.port=32413"

      - "traefik.udp.routers.plex8.entrypoints=plex8"
      - "traefik.udp.routers.plex8.service=plex8"
      - "traefik.udp.services.plex8.loadbalancer.server.port=32414"
volumes: 
  nzbget-downloads:
    external: "${EXTVOLUMES}"
  all-movies:
    external: "${EXTVOLUMES}"
  all-tv:
    external: "${EXTVOLUMES}"
  all-xxx:
    external: "${EXTVOLUMES}"
  all-completed:
    external: "${EXTVOLUMES}"
